### ISSUE TITLE
git action report error

### ISSUE THREAD

**Issue by AlexiaChen** [maguowei/awesome-stars#7]
https://github.com/AlexiaChen/my-repo-stars/runs/6267778587?check_suite_focus=true

```txt
Run starred --username AlexiaChen --repository my-repo-stars --sort --token ${GITHUB_TOKEN} --message 'stars update by github actions cron'
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.[7](https://github.com/AlexiaChen/my-repo-stars/runs/6267778587?check_suite_focus=true#step:5:7).12/x64/bin/starred", line [8](https://github.com/AlexiaChen/my-repo-stars/runs/6267778587?check_suite_focus=true#step:5:8), in <module>
    sys.exit(starred())
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/core.py", line 82[9](https://github.com/AlexiaChen/my-repo-stars/runs/6267778587?check_suite_focus=true#step:5:9), in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/core.py", line [10](https://github.com/AlexiaChen/my-repo-stars/runs/6267778587?check_suite_focus=true#step:5:10)66, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/starred/starred.py", line 72, in starred
    for s in stars:
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/github3/structs.py", line 122, in __iter__
    yield cls(i)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/github3/models.py", line 48, in __init__
    self._update_attributes(json)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/github3/repos/repo.py", line 97, in _update_attributes
    self.owner = users.ShortUser(repo["owner"], self)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/github3/models.py", line 48, in __init__
    self._update_attributes(json)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/github3/users.py", line 3[11](https://github.com/AlexiaChen/my-repo-stars/runs/6267778587?check_suite_focus=true#step:5:11), in _update_attributes
    self.avatar_url = user["avatar_url"]
TypeError: 'NoneType' object is not subscriptable
Error: Process completed with exit code 1.
```

my yaml: 

```yaml
name: update awesome-stars
on:
  workflow_dispatch:
  schedule:
  - cron: 30 0 * * *
jobs:
  awesome-stars:
    name: update awesome-stars
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install starred
    - name: update repo
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      run: starred --username AlexiaChen --repository my-repo-stars --sort --token ${GITHUB_TOKEN} --message 'stars update by github actions cron'
```

**Comment by valetzx** [comment]
别用他演示的 ` run: starred --username AlexiaChen --repository my-repo-stars --sort --token ${GITHUB_TOKEN} --message 'stars update by github actions cron'` 了，直接 `starred --username AlexiaChen --sort > README.md` 将内容输出到README.md之后，用git push推到自己仓库。可以参考一下：https://github.com/valetzx/stars

**Comment by AlexiaChen** [comment]
> 别用他演示的 ` run: starred --username AlexiaChen --repository my-repo-stars --sort --token ${GITHUB_TOKEN} --message 'stars update by github actions cron'` 了，直接 `starred --username AlexiaChen --sort > README.md` 将内容输出到README.md之后，用git push推到自己仓库。可以参考一下：https://github.com/valetzx/stars

你这个只是workaround啊，我的好奇是他的starred报错了。它自己的演示可以成功。我就报奇怪的nonetype错误。你看traceback嘛。

**Comment by valetzx** [comment]
你可以看他的 action 他自己演示的也失败了

**Comment by AlexiaChen** [comment]
> 你可以看他的 action 他自己演示的也失败了

@valetzx 用这个 https://github.com/maguowei/starred/issues/77#issuecomment-1118175723

**Comment by valetzx** [comment]
感谢，但是这也是 workaround（ 我的看起来也不是很复杂

**Comment by AlexiaChen** [comment]
> 感谢，但是这也是 workaround（ 我的看起来也不是很复杂

是的，但是我太懒了，又是git init 和git push的。   我这个人比较懒，不过还是感谢。都是不错的方案。主要是我看这个golang版本的CLI的接口保持一致，改动更少。我改天用Rust写一个，绝对不可能出现python这种问题，我看了python和golang的，源码都很简单。

**Comment by valetzx** [comment]
哈哈好的，自己写的都是最香的。

**Comment by maguowei** [comment]
pls install latest version

`pip install starred==4.0.1`
